name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [8.0, 8.1, 8.2]
        laravel: [9.*, 10.*]

    name: PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        extensions: mbstring, xml
        coverage: none

    - name: Install dependencies
      run: |
        composer require "illuminate/support:${{ matrix.laravel }}" --no-interaction --no-update
        composer update --prefer-dist --no-interaction

    - name: Execute tests
      run: ./vendor/bin/phpunit
